### ISSUE TITLE
Unable to create an android app

### ISSUE THREAD

**Issue by kanavkhurana** [dreamhouseapp/dreamhouse-mobile-app#6]
Hey Chris,

After successfully running the iOS version, I tried to create an apk by running the following command at the project root:
"cordova platform add android@6.1.2"
The Terminal outputs the following:
------------------------------------------------------------------------------------------------
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: org.coenraets.dreamhouse
	Name: DreamHouse
	Activity: MainActivity
	Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.1.2
Installing "com.salesforce" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Installing "cordova-plugin-device" for android
Installing "phonegap-plugin-push" for android
Subproject Path: CordovaLib
Failed to install 'com.salesforce':Error: There was a conflict trying to modify attributes with <edit-config> in plugin com.salesforce. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before com.salesforce can be added. You may use --force to add the plugin and overwrite the conflicting attributes.
    at PlatformMunger.add_plugin_changes (/Users/kanav/dreamhouseionic2sf/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:169:19)
    at /Users/kanav/dreamhouseionic2sf/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:126:25
    at _fulfilled (/Users/kanav/dreamhouseionic2sf/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/kanav/dreamhouseionic2sf/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/kanav/dreamhouseionic2sf/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /Users/kanav/dreamhouseionic2sf/platforms/android/cordova/node_modules/q/q.js:857:14
    at runSingle (/Users/kanav/dreamhouseionic2sf/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/kanav/dreamhouseionic2sf/platforms/android/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Error: There was a conflict trying to modify attributes with <edit-config> in plugin com.salesforce. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before com.salesforce can be added. You may use --force to add the plugin and overwrite the conflicting attributes.
------------------------------------------------------------------------------------------------
Could you help me get past this error please? Thanks!

**Comment by wpf329739489** [comment]
i meet same question ,i want to ask how to resolve it?
